Repository modiharikesh/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#5 Update intro.json
  Task1/intro.json
Labels: hactoberfest, hactoberfest2022

#6 Update intro.json
  Task1/intro.json
Labels: hactoberfest, hactoberfest2022, hactoberfest-accepted

#7 Update socials.js
  Task2/socials.js
Labels: hactoberfest, hactoberfest2022, hactoberfest-accepted

#8 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#21 Update README.md
  Task2/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#20 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#17 Update techStack.html
  Task4/techStack.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 Update techStack.html
  Task4/techStack.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#10 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#72 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#71 Delete ff
  Task2/ff
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#70 Delete xfg
  Task4/xfg
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#69 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#68 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#67 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#66 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#65 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#64 Update README.md
  Task4/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#63 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#62 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#61 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#59 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#58 Update techStack.html
  Task4/techStack.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#57 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#56 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#55 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#54 Update README.md
  Task1/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#53 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#52 Update techStack.html
  Task4/techStack.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#49 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#48 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#47 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#46 Update techStack.html
  Task4/techStack.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#44 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#43 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#42 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#41 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#40 Update README.md
  Task4/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#39 Update techStack.html
  Task4/techStack.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 Update README.md
  Task3/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#36 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#35 Update README.md
  Task1/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#34 Update README.md
  Task4/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#33 Update README.md
  Task3/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#32 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#31 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#30 Update README.md
  Task2/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#29 Update intro.json
  Task1/intro.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Update README.md
  Task2/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#27 Update techStack.html
  Task4/techStack.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Update README.md
  Task1/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 Update education.py
  Task3/education.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#23 Update socials.js
  Task2/socials.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
